# Specify the modifier key which should be used as primary modifier (e.g. for moving
# windows, etc.)
# Default: Mod4
modkey: Mod4
# Configuration for the bar at the top of the screen
bar:
  # Set the height in pixel of the bar. Default: 52
  # This value isn't physical pixel, but dependency independant pixel i.e. pixel
  # on a 96 dpi screen, which will be automatically increased, if you have a hidpi screen
  height: 52
  # Set the widgets to show in the bar on the main display. This should be a
  # comma separated list with the following possibilities:
  # <positive integer> - add spacing of that width
  # displayswitcher: A simple menu to switch which displays to use
  # battery: Battery widget
  # screensaver: A simple button to disable screensaver with one click
  # network: A network monitor showing up and down traffic
  # systray: The systray
  # clock: Clock widget
  # The default value is empty.
  widgets:
# Define some applications, that will be used across the config
applications:
  # Define the launcher, that will be opened on modkey + space.
  # Don't specify to use internal launcher (default)
  launcher:
# Style different theme settings
theme:
  # A path to a wallpaper to use.
  wallpaper:

systray:
  # The pixel density independant size one icon in the systray should get.
  # The systray usualy won't use thta much size if the value is to high. (Default 50)
  size:

# Disable the use of a compositor when set to true. Otherwise compton will be started.
disable_compositor:

# Configure dpi settings for the displays
dpi:
  # Specify a factor that will be multiplied to the x and y dpi setting for all screens
  # that doesn't have a more specific setting.
  xfactor:
  yfactor:
  # You can specify these settings also on a per display basis, by specifying the name
  # of the display (as shown by xrandr) as a key and nest the xfactor and yfactor
  # below this key. These factors will only be applied for dpi values of that screen.

screensaver:
  # Configure how many minutes before the screen will be locked (Default: 10)
  timeout: 10
