# Specify the modifier key which should be used as primary modifier (e.g. for moving
# windows, etc.)
# Default: Mod4
modkey: Mod4
# Configuration for the bar at the top of the screen
bar:
  # Set the height in pixel of the bar. Default: 32
  # This value isn't physical pixel, but dependency independant pixel i.e. pixel
  # on a 96 dpi screen, which will be automatically increased, if you have a hidpi screen
  height: 32
# Define some applications, that will be used across the config
applications:
  # Define the launcher, that will be opened on modkey + space.
  # Don't specify to use internal launcher (default)
  launcher:
# Style different theme settings
theme:
  # A path to a wallpaper to use.
  wallpaper:

# Disable the use of a compositor when set to true. Otherwise compton will be started.
disable_compositor:

# Configure dpi settings for the displays
dpi:
  # Overwrite the automatically detected DPI for an output.
  # Specify here key value pairs where the key is the output name
  # as shown by xrandr and the value a dpi to set.
  # You can use the special key "default" which will overwrite the DPI
  # of all outputs, unless they have a specific overwrite.
  default:

screensaver:
  # Configure how many minutes before the screen will be locked (Default: 10)
  timeout: 10

# A YML list of keyboard layouts, that the user can switch through.
# The first one in this list will be used when starting awesome.
keyboard_layouts:
  - us
